# Generated by Django 4.2.3 on 2023-07-30 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="user",
            new_name="owner",
        ),
    ]
